services:
  - type: web
    name: catalogo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
